# Generated by Django 5.2.8 on 2025-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/%d/')),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
